spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vollmed_api
    username: postgres
    password: postgres

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}