spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vollmed_api
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true